services:

  app:
    image: shanthregistry.azurecr.io/ashwin-web:latest
    depends_on:
       - db
    build : .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring-mysql
  db:
    image: mysql:8.0.27
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kparun
      - MYSQL_USER=kparun
      - MYSQL_PASSWORD=kparun
    networks:
      - spring-mysql  
    ports:
      - "3306:3306"
volumes:
  db_data:
networks:
  spring-mysql:
